remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ''
  - Intro to Docker, Jupyter, Generating Tapis v3 token:
    - Using Docker: block1/intro-to-docker
    - Intro to Jupyter : block1/intro-to-jupyter
    - Generating a Tapis v3 token: block1/tapis-v3-token
    - Intro to Singularity: block1/intro-singularity
  - Intro to Tapis Systems:
    - Intro to Tapis Systems: block3/tapis-systems
  - Intro to Tapis Apps:
    - Intro to Apps: block4/apps
  - Intro to Tapis Jobs:
    - Intro to Tapis Jobs: block4/jobs
    - Job outputs and sharing results: block4/jobs
